CREATE DATABASE KOU3
USE KOU3
CREATE TABLE MUSTERILER(
ID INT IDENTITY(1,1) PRIMARY KEY,
AD VARCHAR(50), 
SOYAD VARCHAR(50),
CINSIYET BIT
)

INSERT INTO MUSTERILER VALUES('AHMET','KARA',1)
INSERT INTO MUSTERILER VALUES('MEHMET','KARA',1)
INSERT INTO MUSTERILER VALUES('YESIM','KARA',0)
INSERT INTO MUSTERILER VALUES('ZEYNEP','KARA',0)
INSERT INTO MUSTERILER VALUES('SEDA','KARA',0)

SELECT * FROM MUSTERILER

CREATE PROC MUSTERI_SAY
@CINSIYET BIT,
@SAY INT OUTPUT
AS 
BEGIN 
	SELECT @SAY=COUNT(ID) FROM MUSTERILER
	WHERE CINSIYET =@CINSIYET
END

DECLARE @X INT
EXEC MUSTERI_SAY 0, @X OUTPUT
PRINT @X

DECLARE @Y INT
EXEC MUSTERI_SAY 1, @Y OUTPUT
IF (@Y=0)
	PRINT 'MUSTERI YOK'
ELSE
	PRINT 'MUSTERI SAYISI: '+CONVERT(VARCHAR,@Y)

CREATE TABLE KULLANICILAR(
KUL_ADI NVARCHAR(20),
PAROLAR NVARCHAR(20)
)

USE KOU3
INSERT INTO KULLANICILAR VALUES('ADMIN','123')
INSERT INTO KULLANICILAR VALUES('USER','124')

SELECT * FROM KULLANICILAR
WHERE KUL_ADI='ADMIN' AND PAROLAR='aaa'or 1=1--' ; --SQL INJECTION HATASI OLUR

CREATE PROC LOGINS
@KULADI NVARCHAR(20),
@PAROLA NVARCHAR(20)
AS 
BEGIN
	SELECT * FROM KULLANICILAR
	WHERE KUL_ADI = @KULADI AND PAROLAR = @PAROLA
END

EXEC LOGINS 'ADMIN','132'

SP_HELPTEXT LOGINS --YARDIMCI KAYNAK OLARAK KULLANILABÝLÝR




SELECT ASCII('A'), ASCII('B')
SELECT CHAR(66), CHAR(65)
SELECT LTRIM('    MERHABA')
SELECT LTRIM(RTRIM('     MERHABA     '))
SELECT KULADI,UPPER(KULADI) AS 'BUYUK HARF',
REVERSE(KULADI) AS 'TERSTEN', LEN(KULADI) AS 'KARAKTER SAYISI',
LEFT(KULADI,2) AS 'SOLTAN ILK KARAKTER', 
CHARINDEX('D', KULADI,1) 
FROM KULLANICILAR

SELECT REPLACE(KULADI, 'AD','X') AS 'KELIME DEGISTIRME',
QUOTENAME(KULADI,'[]') AS KULADI
FROM KULLANICILAR

SELECT STUFF('5451111111', 4,1,'-') FROM KULLANICILAR

SELECT GETDATE(), SYSDATETIME()

PRINT CONVERT(CHAR(30), GETDATE(), 114)



--TRIGGER
USE KOU3
CREATE TABLE PERSONEL(
ID INT PRIMARY KEY IDENTITY(1,1),
ADSOYAD NVARCHAR(50),
MAAS FLOAT,
DEPARTMAN NVARCHAR(50)
)

CREATE TABLE LOGS(
ISLEM NVARCHAR(50),
TARIH DATETIME
)

CREATE TRIGGER TRIGGER1 ON PERSONEL
FOR INSERT
AS 
INSERT INTO LOGS VALUES('KAYIT EKLEME ISLEMI',GETDATE())

INSERT INTO PERSONEL VALUES('AHEMT KARA', 16000,'BILGI ISLEM')
SELECT * FROM personel
SELECT * FROM LOGS

ALTER TRIGGER TRIGGER1 ON PERSONEL 
INSTEAD OF INSERT
AS
INSERT INTO LOGS VALUES('KAYIT EKLEMEK ISLEMI', GETDATE())

INSERT INTO PERSONEL VALUES('MEHMET KARA', 16000,'MUHASEBE')
SELECT * FROM personel
SELECT * FROM LOGS

--SON DERS GENEL ORNEK
