USE KOU1

CREATE TABLE NOTLAR(
OGRENCI_ID INT NOT NULL,
DERS_ID INT NOT NULL,
VIZE FLOAT DEFAULT 0,
FINAL FLOAT DEFAULT 0,
CONSTRAINT OGR_NOT FOREIGN KEY(OGRENCI_ID)
REFERENCES OGRENCILER(OGRENCI_ID)
ON DELETE CASCADE,
CONSTRAINT DERS_NOT FOREIGN KEY (DERS_ID)
REFERENCES DERSLER(DERS_ID)
ON DELETE CASCADE,
CONSTRAINT CHK_VIZE CHECK (VIZE >=0 AND VIZE <=100),
CONSTRAINT CHK_FINAL CHECK (FINAL >=0 AND FINAL <=100)
)

SELECT * FROM NOTLAR
WHERE VIZE BETWEEN 20 AND 80

SELECT * FROM OGRENCILER
WHERE OGRENCI_ID NOT IN (
SELECT OGRENCI_ID FROM NOTLAR
WHERE VIZE > 80)

SELECT  * FROM OGRENCILER
WHERE SOYAD IS NOT NULL

SELECT * FROM NOTLAR
ORDER BY DERS_ID ASC --ASC KÜÇÜKTEN BÜYÜÐE 

SELECT * FROM NOTLAR
ORDER BY DERS_ID DESC --DSC BÜYÜKTEN KÜÇÜÐE

SELECT OGRENCI_ID, DERS_ID, VIZE,FINAL,
VIZE*0.4+FINAL*0.6 AS GECME_NOTU FROM NOTLAR 

SELECT AVG(VIZE*0.4+FINAL*0.6) FROM NOTLAR --FINAL NOTLARININ ORT. HESAPLAMA

SELECT SUM(VIZE*0.4+FINAL*0.6) FROM NOTLAR --FINAL NOTLARININ TOPLAM HESAPLAMA


USE KOU1

SELECT D.DERS_ID, DERS_ADI, VIZE, FINAL FROM DERSLER D JOIN NOTLAR N 
ON
D.DERS_ID = N.DERS_ID








