SELECT * FROM SALES.STOREINFO 
WHERE NAME LIKE 'B%' --B HARFÝ ÝLE BAÞLAYANLARI VERÝR

SELECT * FROM SALES.STOREINFO 
WHERE NAME LIKE '%BIKE%' --ÝÇÝNDE BIKE GEÇENLERÝ GETÝRÝR

SELECT * FROM SALES.STOREINFO 
WHERE NAME LIKE '%COMPANY' --SONU COMPANY ÝLE BÝTENLERÝ GETÝRÝR

SELECT * FROM SALES.STOREINFO 
WHERE YEAROPENED BETWEEN 1990 AND 2000 --BELÝRLENEN SAYI ARALIÐINDAKÝLERÝ GETÝRÝR

SELECT * FROM SALES.STOREINFO 
WHERE NAME LIKE 'B%' AND YEAROPENED = 1990 -- ÝSMÝ B ÝLE BAÞLAYIP YILI B OLANLARI GETÝRÝR

SELECT * FROM SALES.STOREINFO 
WHERE INTERNET = 'DSL' OR INTERNET = 'T1' --INTERNET T1 VEYA DSL OLANLARI GETÝRÝR

UPDATE SALES.STOREINFO SET ANNUALSALES = ANNUALSALES*2
WHERE BUSÝNESSENTÝTYID= 304  --ID 304 OLANANNUALSALES'I ÝKÝ ÝLE ÇARP

DELETE FROM SALES.STOREINFO WHERE BUSÝNESSENTÝTYID=304 --304. ID'YÝ SÝLER

SELECT * FROM SALES.STOREINFO WHERE SPECÝALTY = 'MOUNTAÝN' 
ORDER BY ANNUALSALES --MOUNTAÝN BÝSÝKLET SATANLARIN YILLIK SATIÞINI VERÝR

SELECT * FROM SALES.STOREINFO 
WHERE SPECÝALTY = 'MOUNTAIN' AND NUMBEREMPLOYEES BETWEEN 20 AND 50
ORDER BY YEAROPENED DESC --MOUNTAIN BÝSÝKLET SATAN, ÇALIÞAN SAYISI 20 ÝLE 50 ARASINDA OLANLARI AÇILIÞ TARÝHÝNE GÖRE SIRALAR

-------------------------------------------------------------------

SELECT COUNT(*) AS SALES WHERE ITEMNAME = 'BEYAZÇÝKOLATA' --KAÇ TANE SATILDIÐINI EKRANA VERÝR

SELECT COUNT(*) AS SATISSAYISI, 
MIN(UNITPRICE) AS MINIMUMFIYAT,
MAX(UNITPRICE) AS MAXIMUMFIYAT,
AVG(UNITPRICE) AS ORTALAMAFÝYAT,
AVG(AMOUNT) AS ORTALAMAADET,
SUM(TOTALPROCE) AS TOPLAMSATIS

--FROM SALES WHERE ITEMNAME = 'MAVÝ ÇÝKOLATA' 

GROUP BY ITEMNAME

--------------------------------------------------------------------

--HANGÝ BANKALAR ÝLE EN ÇOK ÇALIÞILIYOR?
SELECT BANKNAME, SUM(ANNUALSALES) AS ANNUALSALES,
COUNT(NAME) STORECOUNT
FROM SALES.STOREINFO
GROUP BY BANKNAME

--ÝÞ TÜRLERÝNÝN DAÐILIMI
SELECT BUSÝNESSTYPE, SUM(ANNUALSALES) AS ANNUALSALES,
COUNT(NAME) STORECOUNT
FORM SALES.STOREINFO
GROUP BY BUSINESSTYPE
ORDER BY COUNT(NAME) DESC




